# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [ ]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
arr = np.random.randint(0, 20, size=(4, 7))
print(arr)


[[ 2 14  9 13  9  2 14]
 [ 4  5 10 15 10  4 11]
 [10 19  3  5 18 17 12]
 [ 6  0 12 16  6  8 16]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
arr = np.random.randint(0, 10, size=(8, 10))
print(arr)
summ = np.sum(arr, axis=1)
# print(summ)
index = np.argmax(summ)
print(f'Строка, в которой сумма значений наибольшая: {arr[index]}')

[[2 4 9 7 2 8 6 2 7 8]
 [2 6 1 4 7 9 8 9 6 2]
 [5 7 4 0 0 4 3 4 5 5]
 [7 8 4 3 4 3 3 5 4 2]
 [1 4 7 1 4 2 2 0 9 9]
 [6 2 9 6 7 4 8 3 3 2]
 [0 9 8 3 5 3 5 1 8 1]
 [7 2 7 4 6 4 0 2 8 0]]
Строка, в которой сумма значений наибольшая: [2 4 9 7 2 8 6 2 7 8]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
a = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]
b =[[3, -1], [2, 1]]
c =[[7, 21], [11, 8], [8, 4]]



## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [ ]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
with open('minutes_n_ingredients.csv', 'r') as file:
    data = file.read()

data = np.loadtxt('minutes_n_ingredients.csv', delimiter=",", skiprows=1, dtype=np.int32)
print(data[0:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
# are the columns correct ??

# max values 
col2_max = np.max(data[:,1])
col3_max = np.max(data[:,2])


print(f'Max value of the second column: {col2_max}')
print(f'Max value of the third column:: {col3_max}')

# average mean 
col2_mean = np.mean(data[:,1])
col3_mean = np.mean(data[:,2])

print(f'Average mean value of the second column: {col2_mean}')
print(f'Average mean value of the third column: {col3_mean}')

# min value 
col2_min = np.min(data[:,1])
col3_min = np.min(data[:,2])
print(f'Min value of the second column: {col2_min}')
print(f'Min value of the third column: {col3_min}')

col2_median = np.median(data[:,1])
col3_median = np.median(data[:,2])

print(f'Median value of the second column: {col2_median}')
print(f'Median value of the third column:: {col3_median}')


Max value of the second column: 2147483647
Max value of the third column:: 39
Average mean value of the second column: 21601.00169
Average mean value of the third column: 9.05528
Min value of the second column: 0
Min value of the third column: 1
Median value of the second column: 40.0
Median value of the third column:: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
data3 = data[data[:,1] <= np.quantile(data[:,1], 0.75)]
print(data3)

65.0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

1. найти рецепты (id то есть первый столбик) для которых значение второго столбика равно 0
2. заменить значение второго ст на 1

In [ ]:
# print(len(data[data[:, 1] == 0]))
# data[:, 1] = np.where(data[:, 1] == 0, 1, 0)
# print(data)

print(np.count_nonzero(data[:,1] == 0))
data[data == 0] = 1

0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
print(len(np.unique(data[:,0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(f'Количество различных значений ингредиентов: {len(np.unique(data[:,2]))}')
print(np.unique(data[:,2]))

Количество различных значений ингредиентов: 37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
data7 = data[data[:,2] <= 5]
print(data7)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
data8 = data[:, 2] / data[:, 1]
print(f'Максимальное: {np.max(data8)}\n{data8}')

Максимальное: 24.0
[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
data9 = data[np.argsort(data[:, 1])][-100:, 2]
print(np.mean(data9))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
print(data[np.random.randint(data.shape[0], size = 10)])

[[ 35975     75      9]
 [464309     50     11]
 [261628     50     10]
 [203869     30     16]
 [122362      5      4]
 [461329      7      6]
 [ 84643     65      3]
 [265838     40     14]
 [150866     75      9]
 [425278     70     11]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
res11 = (data[data[:, 2] < np.mean(data[:, 2])].shape[0] / data.shape[0]) * 100
print(res11)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
data_booli = (data[:,1] <= 20) & (data[:,2] <= 5)
data12 = np.hstack((data, data_booli[:, np.newaxis]))
print(data12)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
print(data12[data12[:,3] == 1].shape[0] / data.shape[0] * 100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.